<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>MediaBrowser.Controller</AssemblyName>
    <RootNamespace>MediaBrowser.Controller</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MediaBrowser.Model\MediaBrowser.Model.csproj" />
  </ItemGroup>
</Project>
